on:
  push:
    branches: [ main ]

name: AzureMLTrain

jobs:
  setup-aml-and-create-pipeline:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}
      RESOURCE_GROUP: "Cybertron-RG"
      AML_WORKSPACE: "Cybertron"

    steps:
    - name: Checkout Repository
      id: checkout_repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Azure CLI script - Run AZ ML Commands
      uses: azure/CLI@v1
      with:
        azcliversion: 2.35.0
        inlineScript: echo "Hello World"
    - run: az extension add -n ml -y
    - run: |
          az config set defaults.workspace=$AML_WORKSPACE
          az config set defaults.group=$RESOURCE_GROUP
          az account set -s $AZURE_SUBSCRIPTION         
    - run: |
          az ml environment create --file src/create-environment.yml 
      continue-on-error: true
    - run: |
          az ml compute create --file src/create-compute.yml 
    - run: |
          az ml job create --file src/pipeline/pipeline.yml