$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: Lego-Pipeline
description: Pipeline to create a Lego Classifier in PyTorch

settings:
  default_datastore: azureml:workspaceartifactstore
  default_compute: azureml:UltraMagnus

inputs:
  training_data:
    mode: ro_mount
    path: azureml:LegoFigures:3

jobs:
  train_model:
    type: command
    component: file:components/train.yml
    inputs:
      training_data: ${{parent.inputs.training_data}}
      epochs: 16
      tag: "TEST7"
    outputs:
      train_output: 
        mode: upload
      
  register_pytorch:
    type: command
    component: file:components/register.yml
    inputs:
      model_assets_path: ${{parent.jobs.train_model.outputs.train_output}}
      model_name: "pipeline-simpsons-pytorch"
      model_file_name: "model.pth"

  convert_to_onnx:
    type: command
    component: file:components/onnx.yml
    inputs:
      input_assets_path: ${{parent.jobs.train_model.outputs.train_output}}
    outputs:
      output_assets_path: 
        mode: upload

  register_onnx:
    type: command
    component: file:components/register.yml
    inputs:
      model_assets_path: ${{parent.jobs.convert_to_onnx.outputs.output_assets_path}}
      model_name: "pipeline-simpsons-onnx"
      model_file_name: "model.onnx"